include:
  - path: ./postgres.yaml
  - path: ./imgsrv.yaml
  - path: ./observability.yaml
services:
  goweb:
    build: .
    ports:
      - "${APP_PORT}:8181"
    environment:
      - PGRS_HOST=${PGRS_HOST}
      - PGRS_PORT=${PGRS_PORT}
      - POSTGRES_DB=${PGRS_DB}
      - POSTGRES_USER=${PGRS_USER}
      - POSTGRES_PASSWORD=${PGRS_PASS}
    depends_on:
      postgres:
        condition: service_healthy
      # imageserver:
      #   condition: service_healthy
