service:
  flush: 1
  log_level: info
  parsers_file: /fluent-bit/etc/parsers.conf

pipeline:
  inputs:
    - name: tail
      path: /var/lib/docker/containers/*/*.log
      tag: docker.*
      parser: docker

  filters:
    - name: docker
      match: docker.*
    - name: parser
      match: docker.*
      key_name: log
      reserve_data: true
      parser: json

  outputs:
    - name: stdout
      match: "*"

