services:
  fluentbit:
    image: fluent/fluent-bit:4.0
    environment:
      - FLB_CONFIG_FILE=/fluent-bit/etc/fluent-bit.yaml
    volumes:
      - ./fluent-bit.yaml:/fluent-bit/etc/fluent-bit.yaml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - goweb
