ALTER TABLE texts DROP CONSTRAINT IF EXISTS fk_image_bt;
ALTER TABLE texts DROP CONSTRAINT IF EXISTS fk_image_ref;
ALTER TABLE images_bt DROP CONSTRAINT IF EXISTS fk_text;
ALTER TABLE images_ref DROP CONSTRAINT IF EXISTS fk_text;

DROP TABLE IF EXISTS images_bt;
DROP TABLE IF EXISTS images_ref;
DROP TABLE IF EXISTS texts;